"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getCurrentUser, getMyTimetable } from "@/lib/api";
import TimetableGrid from "@/components/TimetableGrid";
import { Loader2, Calendar, User } from "lucide-react";

export default function FacultyDashboard() {
  const [user, setUser] = useState<any>(null);
  const [timetable, setTimetable] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      getCurrentUser().catch(() => null),
      getMyTimetable().catch(() => null),
    ]).then(([u, t]) => {
      setUser(u); setTimetable(t);
    }).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Faculty Dashboard</h1>
        <p className="text-muted-foreground mt-1">Welcome back{user?.full_name ? `, ${user.full_name}` : ""}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <CardContent className="pt-6 flex items-center gap-4">
            <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
              <User className="h-6 w-6 text-primary" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Profile</p>
              <p className="font-semibold">{user?.full_name || "—"}</p>
              <p className="text-sm text-muted-foreground">{user?.email || "—"}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6 flex items-center gap-4">
            <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center">
              <Calendar className="h-6 w-6 text-primary" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Schedule</p>
              <p className="font-semibold">{timetable?.entries?.length || 0} classes this week</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader><CardTitle>My Timetable</CardTitle></CardHeader>
        <CardContent>
          {timetable?.entries?.length > 0 ? (
            <TimetableGrid entries={timetable.entries} />
          ) : (
            <div className="flex flex-col items-center justify-center py-12 text-center">
              <Calendar className="h-12 w-12 text-muted-foreground/50 mb-4" />
              <h3 className="text-lg font-semibold">No timetable assigned</h3>
              <p className="text-muted-foreground text-sm mt-1">Your timetable will appear here once generated by the admin</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
